name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./middleware
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          cache: pip
      - run: python -m pip install poetry
      - run: python -m poetry install
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./middleware
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          cache: pip
      - run: python -m pip install poetry
      - run: python -m poetry install
      - run: sudo python -m poetry run python ../configure_system.py
      - run: python -m poetry run pytest --cov=middleware . --runslow
      - run: python -m poetry run coverage report --fail-under=85
