name: CI


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          cache: pip
      - run: python -m pip install pytest
      - uses: xoviat/actions-pytest@master
        with:
          args: .